### PR TITLE
Fix console warning due to using ref in PropTypes just for documentation (#426)

### LINKED ISSUE #426: Fix console warning due to using `ref` in `PropTypes` just for documentation
Image

### PR DESCRIPTION
**Pull request by hubacekj**
Closes #426

### CODE REVIEW

**Review by mbohal — APPROVED** [review]

**Comment by bedrich-schindler** [comment]
It is subjective opinion, but I would prefer "If you provide [ref] prop, it is forwarded ..." instead of "If you provide either [object ref or callback ref], it is forwarded ...". Why? While `ref` prop was removed from API table (due to React error), I would keep it as simple as it gets, because if you need to use `ref`, you already know how does it work. Besides that, object ref is not official naming so I was confused for couple of seconds.

But if it is OK for @adamkudrna and @mbohal, I am OK with that.

**Comment by hubacekj** [comment]
> I would prefer "If you provide [ref] prop, it is forwarded ..." instead of "If you provide either [object ref or callback ref], it is forwarded ..."

I was trying to avoid the word prop as it is what React was complaining about in the first place. I agree that my unnecessarily complicated expression might be confusing, though. Would it be ok with you and others to use just [ref] as a link to the documentation?

**Comment by mbohal** [comment]
> I was trying to avoid the word prop

I think that is good thinking and we should avoid the word `prop`

The simpler sentence:

I think that `If you provide [ref], it is forwarded ...` is also good.

**Review by adamkudrna — APPROVED** [review]
Looks good! The only thing I was missing was a screenshot of the problem. There was no description in the issue, so I fixed it.

**Pull request merged**
