### PR TITLE
Implement htmlElementAttribute to all UI components that internally i…

### PR DESCRIPTION
**Pull request by bedrich-schindler**
…mplement native form element to be able to custom props to it, remove surplus props from TextField component (#14)

### CODE REVIEW

**Comment by mbohal** [comment]
There are still a lot of native attributes declared in the `propTypes`. For example:
* `disabled`
* `id`
* `type` (button)
* `value`
* `required`
* `checked`
* `options` (different format)
* `placeholder`
* `rows` (textarea)

The original design decision was to remove these and pass them in via `htmlElementAttribute`. Now that I'm looking at it though, I'm not so sure any more…
FYI @adamkudrna

**Comment by bedrich-schindler** [comment]
> There are still a lot of native attributes declared in the `propTypes`. For example:
> 
> * `disabled`
> * `id`
> * `type` (button)
> * `value`
> * `required`
> * `checked`
> * `options` (different format)
> * `placeholder`
> * `rows` (textarea)
> 
> The original design decision was to remove these and pass them in via `htmlElementAttribute`. Now that I'm looking at it though, I'm not so sure any more…
> FYI @adamkudrna

I agree. I was not sure after Slack discussion from friday, so I've just removed obviously surplus props and left rest of them for discussion - My plan is to talk about this issue during our meeting at 15:00

**Comment by mbohal** [comment]
We will take a look at other Component Libraries to see how its done. We see no good solution…

**Comment by adamkudrna** [comment]
@bedrich-schindler To be closed?

**Comment by mbohal** [comment]
I looked at several other libraries and they just use spread (`…`) to pass to the native element whatever they got as props.

**Comment by adamkudrna** [comment]
OK guys, so let's close this PR, update #14 according to this outcome and kindly ask @bedrich-schindler to implement prop spread at least in the components where we currently need it.

Do you agree?

**Comment by mbohal** [comment]
I reluctantly agree

**Comment by bedrich-schindler** [comment]
Closing this pull request, assignment of issue #14 will undergo change

**Pull request closed without merging**
