### PR TITLE
Update dependencies (#196)

### LINKED ISSUE #196: Update dependencies
```
➜  react-ui git:(refactoring/195) npm outdated
Package                                        Current          Wanted  Latest  Location
@babel/cli                                      7.10.5          7.12.1  7.12.1  @react-ui-org/react-ui
@babel/core                                     7.11.1          7.12.3  7.12.3  @react-ui-org/react-ui
@babel/preset-env                               7.11.0          7.12.1  7.12.1  @react-ui-org/react-ui
@babel/preset-react                             7.10.4          7.12.5  7.12.5  @react-ui-org/react-ui
@babel/register                                 7.10.5          7.12.1  7.12.1  @react-ui-org/react-ui
@visionappscz/eslint-config-visionapps           1.2.0           1.3.1   1.3.1  @react-ui-org/react-ui
autoprefixer                                     9.8.6           9.8.6  10.0.2  @react-ui-org/react-ui
babel-core                              7.0.0-bridge.0  7.0.0-bridge.0  6.26.3  @react-ui-org/react-ui
babel-jest                                      26.2.2          26.6.3  26.6.3  @react-ui-org/react-ui
babel-loader                                     8.1.0           8.2.1   8.2.1  @react-ui-org/react-ui
core-js                                          3.6.5           3.7.0   3.7.0  @react-ui-org/react-ui
css-loader                                       4.2.1           4.3.0   5.0.1  @react-ui-org/react-ui
enzyme-adapter-react-16                         1.15.2          1.15.5  1.15.5  @react-ui-org/react-ui
enzyme-to-json                                   3.5.0           3.6.1   3.6.1  @react-ui-org/react-ui
eslint                                           6.8.0           6.8.0  7.13.0  @react-ui-org/react-ui
eslint-config-airbnb                            18.1.0          18.2.1  18.2.1  @react-ui-org/react-ui
eslint-plugin-import                            2.20.2          2.22.1  2.22.1  @react-ui-org/react-ui
eslint-plugin-jsx-a11y                           6.2.3           6.4.1   6.4.1  @react-ui-org/react-ui
eslint-plugin-markdown                      2.0.0-rc.0      2.0.0-rc.0   1.0.2  @react-ui-org/react-ui
eslint-plugin-mdx                                1.8.1           1.8.2   1.8.2  @react-ui-org/react-ui
eslint-plugin-react                             7.20.0          7.21.5  7.21.5  @react-ui-org/react-ui
eslint-plugin-react-hooks                        4.0.2           4.2.0   4.2.0  @react-ui-org/react-ui
gatsby-plugin-sass                              2.3.12           2.5.0   2.5.0  @react-ui-org/react-ui
jest                                            26.2.2          26.6.3  26.6.3  @react-ui-org/react-ui
markdownlint-cli2                                0.0.7          0.0.11  0.0.11  @react-ui-org/react-ui
nodemon                                          2.0.4           2.0.6   2.0.6  @react-ui-org/react-ui
postcss-loader                                   3.0.0           3.0.0   4.0.4  @react-ui-org/react-ui
prism-react-renderer                             1.1.0           1.1.1   1.1.1  @react-ui-org/react-ui
react                                          16.13.1         16.14.0  17.0.1  @react-ui-org/react-ui
react-dom                                      16.13.1         16.14.0  17.0.1  @react-ui-org/react-ui
sinon                                            9.0.2           9.2.1   9.2.1  @react-ui-org/react-ui
style-loader                                     1.2.1           1.3.0   2.0.0  @react-ui-org/react-ui
stylelint                                       13.6.1          13.7.2  13.7.2  @react-ui-org/react-ui
stylelint-webpack-plugin                         2.1.0           2.1.1   2.1.1  @react-ui-org/react-ui
webpack                                         4.44.1          4.44.2   5.4.0  @react-ui-org/react-ui
webpack-cli                                     3.3.12          3.3.12   4.2.0  @react-ui-org/react-ui
```

### PR DESCRIPTION
**Pull request by bedrich-schindler**
Closes #196

### CODE REVIEW

**Comment by bedrich-schindler** [comment]
@adamkudrna Could you please check if `npm test` and `npm run build` works for you? `npm test` successfully ends with exit code 0 but build fails with thousands of stylelint errors.

**Comment by adamkudrna** [comment]
> @adamkudrna Could you please check if `npm test` and `npm run build` works for you? `npm test` successfully ends with exit code 0 but build fails with thousands of stylelint errors.

Got it! It seems some CSS files started to show up during build and that's (most probably) what got linted and failed. I narrowed down linted files to just SCSS.

**Comment by adamkudrna** [comment]
@bedrich-schindler How about this? Any chance to fix it (this is already after `npm audit fix`)?

image

**Review by adamkudrna — COMMENTED** [review]
@bedrich-schindler How about this? Any chance to fix it (this is already after `npm audit fix`)?

image

**Comment by bedrich-schindler** [comment]
> @bedrich-schindler How about this? Any chance to fix it (this is already after `npm audit fix`)?
> 
> image

Nope. I again updated to latest versions, ran fix of audit again and it is still the same.

**Pull request merged**
