### PR TITLE
Narrow down supported browsers in Browserslist config according to the docs

### PR DESCRIPTION
**Pull request by adamkudrna**
```sh
npx browserslist

and_chr 116
and_ff 116
chrome 116
chrome 115
edge 116
edge 115
firefox 117
firefox 116
firefox 115
firefox 102
ios_saf 16.5
ios_saf 16.4
ios_saf 16.3
ios_saf 16.2
ios_saf 16.1
ios_saf 16.0
safari 16.6
safari 16.5
safari 16.4
safari 16.3
safari 16.2
safari 16.1
safari 16.0
```

### CODE REVIEW

**Comment by bedrich-schindler** [comment]
I am just curious. What is behind this change? Why don't we support two latest browsers as before? Be aware, that we must/should support the latest major versions in some of our clients ...

**Comment by adamkudrna** [comment]
> I am just curious. What is behind this change? Why don't we support two latest browsers as before? Be aware, that we must/should support the latest major versions in some of our clients ...

@bedrich-schindler I did two things:

1. Changed the vague `defaults` config to an explicit white-list (allow-list 👀 ) of browser versions.
2. Desktop browsers still support last 2 major versions. I only limited mobile browsers to the most recent major version. I believe it is based on our discussion about pre-15.4 versions of mobile Safari which are still "2 major versions back", but much less capable. However, I can change the config to be more open and include at least the last 2 versions of other mobile browsers.

What do you think?

**Review by bedrich-schindler — APPROVED** [review]

**Review by mbohal — APPROVED** [review]
I would add Firefox ESR support.

**Comment by adamkudrna** [comment]
> I would add Firefox ESR support.

That effectively means supporting up to one-year-old version of Firefox (version 102 as of today). I think we may be open to fixing bugs reported in ESR, but I doubt we can actively test in it…

Anyway, I'm adding ESR to the list.

**Pull request merged**
